config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :dashboard do
    resources :events
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard/events_controller.rb
class Dashboard::EventsController < ApplicationController

  before_action :authenticate_user!



  before_action :load_event, only: [:show, :edit, :update, :destroy]


  

  def load_event
    @event = current_user.events.find(params[:id])
  end

  def index
    @events = current_user.events.page(params[:page])

    respond_to do |format|
      format.js
      format.html {render 'all.haml'}
    end
  end

  def new
    @event = Event.new(user: current_user)
    respond_to do |format|
      format.js
    end
  end

  def create
    @event = Event.create(event_params.merge!(user: current_user))
    respond_to do |format|
      if @event.save
        format.js
      else
        flash[:alert] = "Oops, your event could not be saved."
        format.js
      end
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if !@event.update(event_params)
        flash[:alert] = "Event could not be saved"
      end
      format.js {}
    end
  end

  def destroy
    respond_to do |format|
      begin
        @event.destroy
      rescue StandardError => e
        flash[:alert] = "Event could not be deleted"
      end
      format.js {}
    end
  end

  def event_params
    params.require(:event).permit( [:user_id, :name, :start_at, :end_at, :promote_on,
                                    :description] )
  end

  def default_colspan
    6
  end

  def namespace
    
      "dashboard/"
    
  end


  def common_scope
    @nested_args
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/events/_edit.haml
= render partial: "common/common_edit_form", locals: {singular: 'event', object: event, url: dashboard_event_path(@event), colspan: colspan}

app/views/dashboard/events/_form.haml
.row
  .form-group.col-md-4
    = f.collection_select(:user_id, User.all, :id, :name, {:prompt => true}, class: 'form-control')
    %label.small.form-text.text-muted
      User
.row
  .form-group.col-md-4
    = f.text_field :name, size: 40, class: 'form-control'
    %label.form-text
      Name

.row
  .form-group.col-md-4
    = f.text_field :start_at, class: 'form-control', type: 'datetime-local'
    %label.form-text
      Start at

.row
  .form-group.col-md-4
    = f.text_field :end_at, class: 'form-control', type: 'datetime-local'
    %label.form-text
      End at


.row
  .form-group.col-md-4
    = f.text_field :description, size: 40, class: 'form-control'
    %label.form-text
      Description

app/views/dashboard/events/_line.haml
%tr{'data-id': event.id, 'data-edit': 'false'}
  %td
    = event.user.to_label
  %td
    = event.name
  %td
    = event.start_at
  %td
    = event.end_at

  %td
    = event.description
  %td
    = link_to "Edit <i class='fa fa-1x fa-list-alt'></i>".html_safe, edit_dashboard_event_path(event), remote: true , disable_with: "Loading...", class: "edit-event-button btn btn-primary pull-right "

app/views/dashboard/events/_list.haml
= link_to "New event", new_dashboard_event_path(), disable_with: "Loading...", remote: true, class: "new-event-button btn btn-primary pull-right"

.clearfix
.new-event-form{style: "display: none; position: relative;"}



%table.table.table-striped.event-table
  %thead
    %tr
      %th{:scope => "col"} User      %th{:scope => "col"} Name      %th{:scope => "col"} Start at      %th{:scope => "col"} End at      %th{:scope => "col"} Promote on      %th{:scope => "col"} Description



  %tbody
    - if events.empty?
      None
    - events.each do |event|
      = render partial: 'dashboard/events/line', locals: {event: event,  }

app/views/dashboard/events/_new.haml
= render partial: "common/common_new_form", locals: {singular: 'event', plural: "events", object: @event, url: dashboard_events_path()}

app/views/dashboard/events/all.haml
.container-fluid
  .row
    .col-md-12
      = render partial: "dashboard/events/list", locals: {events: current_user.events.order("created_at DESC").page(1)}

app/views/dashboard/events/create.js.erb
<%= render partial: 'common/common_create', locals: {object: @event, singular: "event", plural: "events"} %>

app/views/dashboard/events/destroy.js.erb
<%= render partial: 'common/common_destroy', locals: {object: @event, singular: "event", plural: "events", all_objects: current_user.events} %>

app/views/dashboard/events/edit.js.erb
<%= render partial: 'common/common_edit', locals: {object: @event, singular: "event", plural: "events", url: dashboard_event_path(@event)} %>

app/views/dashboard/events/index.js.erb
<%= render partial: 'common/common_index', locals: {objects: @events, singular: "event", plural: "events"} %>

app/views/dashboard/events/new.js.erb
<%= render partial: 'common/common_new', locals: {object: @event, singular: "event", plural: "events"} %>

app/views/dashboard/events/update.js.erb
<%= render partial: 'common/common_update', locals: {object: @event, singular: "event",
plural: "events",
 url: dashboard_event_path(@event),
 pass_through_locals: {
  
}} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyGreatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>